definitions:
  response.FacadeResponse:
    properties:
      CallbackId:
        type: string
      Code:
        type: string
      Comment:
        type: string
      CreatedAt:
        type: string
      ExecutedCommand:
        type: string
      Success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /device/command:
    post:
      consumes:
      - application/json
      description: Enqueue command to device
      parameters:
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: command
        in: formData
        name: command
        required: true
        type: string
      - description: callback_id
        in: formData
        name: callback_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Send command to device
      tags:
      - device
  /device/directcommand:
    post:
      consumes:
      - application/json
      description: Send packet to IP:port
      parameters:
      - description: ip
        in: formData
        name: ip
        required: true
        type: string
      - description: port
        in: formData
        name: port
        required: true
        type: integer
      - description: command
        in: formData
        name: command
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Send command to IP and port using UDP protocol
      tags:
      - device
  /device/identity_exists:
    get:
      consumes:
      - application/json
      description: Checks device by device identity
      parameters:
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Checks device is currently connected to service
      tags:
      - device
  /device/locate:
    get:
      consumes:
      - application/json
      description: Returns locate command
      parameters:
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Get locate command
      tags:
      - device
    post:
      consumes:
      - multipart/form-data
      description: Enqueue location request to device
      parameters:
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: callback_id
        in: formData
        name: callback_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Send locate request
      tags:
      - device
  /device/update_config:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Enqueue configuration to device
      parameters:
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: callback_id
        in: formData
        name: callback_id
        required: true
        type: string
      - collectionFormat: multi
        description: config
        in: formData
        items:
          type: string
        name: config
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Send configuration to device
      tags:
      - device
swagger: "2.0"
