definitions:
  response.FacadeResponse:
    properties:
      CallbackId:
        type: string
      Code:
        type: string
      Comment:
        type: string
      CreatedAt:
        type: string
      ExecutedCommand:
        type: string
      Success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /device/update_config:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Enqueue configuration to device
      parameters:
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: callback_id
        in: formData
        name: callback_id
        required: true
        type: string
      - collectionFormat: multi
        description: config
        in: formData
        items:
          type: string
        name: config
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FacadeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.FacadeResponse'
      summary: Send configuration to device
      tags:
      - device
swagger: "2.0"
